// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQlA373rMFmmQYeOCJaJwqi4ihI5_z1Vc',
    appId: '1:1084796413130:web:3f378ae7cc351118a98033',
    messagingSenderId: '1084796413130',
    projectId: 'accr-d1d4a',
    authDomain: 'accr-d1d4a.firebaseapp.com',
    storageBucket: 'accr-d1d4a.appspot.com',
    measurementId: 'G-T3DN7WNYN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT-mmBgkHKiTaHuMBUxyuIWKQO25ulaCU',
    appId: '1:1084796413130:android:9dfd53b095819d5aa98033',
    messagingSenderId: '1084796413130',
    projectId: 'accr-d1d4a',
    storageBucket: 'accr-d1d4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACKIMHU_Vt3THi0BazYX3oNhOIQMY4zlQ',
    appId: '1:1084796413130:ios:6ce0dc11b61398f4a98033',
    messagingSenderId: '1084796413130',
    projectId: 'accr-d1d4a',
    storageBucket: 'accr-d1d4a.appspot.com',
    iosClientId: '1084796413130-sfk0mup16uvfv75ch0s0nbdj5i5n9pmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.alo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACKIMHU_Vt3THi0BazYX3oNhOIQMY4zlQ',
    appId: '1:1084796413130:ios:93780ca8114e12daa98033',
    messagingSenderId: '1084796413130',
    projectId: 'accr-d1d4a',
    storageBucket: 'accr-d1d4a.appspot.com',
    iosClientId: '1084796413130-1g0o56re2oh94erdmupcke15qvqmufnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.alo.RunnerTests',
  );
}
